# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'savedialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_saveDialog(object):
    def setupUi(self, saveDialog):
        saveDialog.setObjectName("saveDialog")
        saveDialog.resize(279, 104)
        saveDialog.setMinimumSize(QtCore.QSize(279, 104))
        saveDialog.setMaximumSize(QtCore.QSize(279, 104))
        self.saveOKButton = QtWidgets.QPushButton(saveDialog)
        self.saveOKButton.setGeometry(QtCore.QRect(110, 70, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.saveOKButton.setFont(font)
        self.saveOKButton.setObjectName("saveOKButton")
        self.saveDisplay = QtWidgets.QLabel(saveDialog)
        self.saveDisplay.setGeometry(QtCore.QRect(90, 30, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.saveDisplay.setFont(font)
        self.saveDisplay.setText("")
        self.saveDisplay.setObjectName("saveDisplay")

        self.retranslateUi(saveDialog)
        QtCore.QMetaObject.connectSlotsByName(saveDialog)

    def retranslateUi(self, saveDialog):
        _translate = QtCore.QCoreApplication.translate
        saveDialog.setWindowTitle(_translate("saveDialog", "File I/O"))
        self.saveOKButton.setText(_translate("saveDialog", "OK"))
